module.exports = {
  apps: [
    {
      name: 'btc-liquidity-web',
      namespace: 'btc-liquidity',
      cwd: '/home/thangnguyen/project/btc-liquidity-proxy',
      script: 'src/server.js',
      interpreter: '/home/thangnguyen/.nvm/versions/node/v22.16.0/bin/node',
      node_args: '--max-old-space-size=16384',
      exec_mode: 'fork',
      instances: 1,
      watch: false,
      autorestart: true,
      min_uptime: '30s',
      max_restarts: 30,
      exp_backoff_restart_delay: 5000,
      max_memory_restart: '18G',
      kill_timeout: 30000,
      listen_timeout: 30000,
      treekill: true,
      time: true,
      merge_logs: true,
      vizion: false,
      env: {
        NODE_ENV: 'production',
        PORT: '19082',
      },
    },
    {
      name: 'btc-liquidity-watchdog',
      namespace: 'btc-liquidity',
      cwd: '/home/thangnguyen/project/btc-liquidity-proxy',
      script: 'scripts/pm2-health-watchdog.mjs',
      interpreter: '/home/thangnguyen/.nvm/versions/node/v22.16.0/bin/node',
      exec_mode: 'fork',
      instances: 1,
      watch: false,
      autorestart: true,
      min_uptime: '10s',
      max_restarts: 30,
      exp_backoff_restart_delay: 5000,
      max_memory_restart: '256M',
      kill_timeout: 10000,
      time: true,
      merge_logs: true,
      vizion: false,
      env: {
        NODE_ENV: 'production',
        WATCHDOG_URL: 'http://127.0.0.1:19082/healthz',
        WATCHDOG_PM2_PROCESS: 'btc-liquidity-web',
        WATCHDOG_INTERVAL_MS: '15000',
        WATCHDOG_TIMEOUT_MS: '5000',
        WATCHDOG_FAILURE_LIMIT: '2',
        WATCHDOG_STARTUP_GRACE_MS: '3600000',
        WATCHDOG_RESTART_GRACE_MS: '3600000',
      },
    },
  ],
};
